//! R2 upload helpers for publish snapshot artefacts.
//!
//! The snapshot builder produces pure data plans. This module is the
//! small I/O boundary that writes those plans into
//! [`PublishStorage`]: text file previews as raw bytes and the
//! revision `code-manifest.json` as JSON.

use crate::{
    internal::publish::{
        ai_export::{
            AiExportPlan, publish_ai_bundle_relative_key, publish_ai_graph_relative_key,
            publish_ai_index_relative_key, publish_ai_object_relative_key,
        },
        contract::{
            AiObjectLayer, FileDisplayMode, PUBLISH_SCHEMA_VERSION, PublishRefsIndex,
            PublishSiteLatest, RedactionMode, RefType,
        },
        snapshot::{RevisionArtifactPlan, SnapshotBuildError, SnapshotPlan},
    },
    utils::{
        d1_client::{
            PublishAiObjectRow, PublishAiVersionRow, PublishFileRow, PublishRefRow,
            PublishRevisionRow,
        },
        storage::publish_storage::{PublishStorage, PublishStorageError},
    },
};

pub const PUBLISH_REFS_INDEX_RELATIVE_KEY: &str = "refs.json";
pub const PUBLISH_SITE_LATEST_RELATIVE_KEY: &str = "latest.json";

/// Summary of R2 objects written for one revision artefact plan.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RevisionArtifactUploadSummary {
    pub code_manifest_key: String,
    pub code_manifest_uploaded: bool,
    pub text_blob_count: usize,
    pub text_blob_uploaded_count: usize,
    pub text_blob_skipped_count: usize,
    pub text_blob_keys: Vec<String>,
}

/// Options controlling revision artifact upload idempotency.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RevisionArtifactUploadOptions {
    /// Re-write objects even when the content-addressed key already exists.
    pub force: bool,
}

/// D1 rows generated for one revision artefact plan.
#[derive(Clone, Debug)]
pub struct RevisionD1Rows {
    pub revision: PublishRevisionRow,
    pub files: Vec<PublishFileRow>,
}

/// Site-level refs/latest artifacts generated by an all-refs sync.
#[derive(Clone, Debug)]
pub struct SiteIndexArtifacts {
    pub refs_index: PublishRefsIndex,
    pub latest: PublishSiteLatest,
    pub ref_rows: Vec<PublishRefRow>,
}

/// Summary of AI object-model artefacts written for one revision.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AiExportArtifactUploadSummary {
    pub index_uploaded: bool,
    pub graph_uploaded: bool,
    pub bundle_uploaded: bool,
    pub object_count: usize,
    pub object_uploaded_count: usize,
    pub object_skipped_count: usize,
    pub object_keys: Vec<String>,
}

/// D1 rows generated for one AI export plan.
#[derive(Clone, Debug)]
pub struct AiExportD1Rows {
    pub objects: Vec<PublishAiObjectRow>,
    pub version: PublishAiVersionRow,
}

/// Errors surfaced while converting artefact plans into D1 row values.
#[derive(Debug, thiserror::Error)]
pub enum RevisionD1RowsError {
    #[error("publish revision file count {count} exceeds D1 integer range")]
    FileCountTooLarge { count: usize },
    #[error("publish file {path:?} has size {size_bytes} which exceeds D1 integer range")]
    FileSizeTooLarge { path: String, size_bytes: u64 },
}

/// Errors surfaced while building site-level refs/latest artifacts.
#[derive(Debug, thiserror::Error)]
pub enum SiteIndexArtifactError {
    #[error(transparent)]
    Snapshot(#[from] SnapshotBuildError),
    #[error("site index requires a default ref")]
    MissingDefaultRef,
    #[error("site index requires the default ref to resolve to a latest revision")]
    MissingLatestRevision,
}

/// Errors surfaced while converting AI artefact plans into D1 row values.
#[derive(Debug, thiserror::Error)]
pub enum AiExportD1RowsError {
    #[error("AI export object count {count} exceeds D1 integer range")]
    ObjectCountTooLarge { count: usize },
    #[error("AI export plan does not contain a bundle entry")]
    MissingBundle,
}

/// Write a revision code snapshot to publish storage.
///
/// Binary, too-large and ignored files are intentionally not written
/// as R2 blobs; they are represented only in `code-manifest.json` and
/// later D1 file metadata rows.
pub async fn upload_revision_artifacts(
    storage: &PublishStorage,
    plan: &RevisionArtifactPlan,
) -> Result<RevisionArtifactUploadSummary, PublishStorageError> {
    upload_revision_artifacts_with_options(storage, plan, RevisionArtifactUploadOptions::default())
        .await
}

/// Write a revision code snapshot to publish storage with explicit
/// idempotency controls.
pub async fn upload_revision_artifacts_with_options(
    storage: &PublishStorage,
    plan: &RevisionArtifactPlan,
    options: RevisionArtifactUploadOptions,
) -> Result<RevisionArtifactUploadSummary, PublishStorageError> {
    let mut text_blob_keys = Vec::with_capacity(plan.text_blobs.len());
    let mut text_blob_uploaded_count = 0usize;
    let mut text_blob_skipped_count = 0usize;
    for blob in &plan.text_blobs {
        if options.force || !storage.head(&blob.relative_key).await? {
            storage.put_bytes(&blob.relative_key, &blob.bytes).await?;
            text_blob_uploaded_count += 1;
        } else {
            text_blob_skipped_count += 1;
        }
        text_blob_keys.push(blob.object_key.clone());
    }
    let code_manifest_uploaded =
        options.force || !storage.head(&plan.code_manifest_relative_key).await?;
    if code_manifest_uploaded {
        storage
            .put_json(&plan.code_manifest_relative_key, &plan.code_manifest)
            .await?;
    }

    Ok(RevisionArtifactUploadSummary {
        code_manifest_key: plan.code_manifest_key.clone(),
        text_blob_count: text_blob_keys.len(),
        code_manifest_uploaded,
        text_blob_uploaded_count,
        text_blob_skipped_count,
        text_blob_keys,
    })
}

/// Write all-refs site indexes to publish storage.
pub async fn upload_site_index_artifacts(
    storage: &PublishStorage,
    artifacts: &SiteIndexArtifacts,
) -> Result<(), PublishStorageError> {
    storage
        .put_json(PUBLISH_REFS_INDEX_RELATIVE_KEY, &artifacts.refs_index)
        .await?;
    storage
        .put_json(PUBLISH_SITE_LATEST_RELATIVE_KEY, &artifacts.latest)
        .await?;
    Ok(())
}

/// Write AI object-model artefacts to publish storage.
pub async fn upload_ai_export_artifacts(
    storage: &PublishStorage,
    plan: &AiExportPlan,
) -> Result<AiExportArtifactUploadSummary, PublishStorageError> {
    upload_ai_export_artifacts_with_options(storage, plan, RevisionArtifactUploadOptions::default())
        .await
}

/// Write AI object-model artefacts with explicit idempotency controls.
pub async fn upload_ai_export_artifacts_with_options(
    storage: &PublishStorage,
    plan: &AiExportPlan,
    options: RevisionArtifactUploadOptions,
) -> Result<AiExportArtifactUploadSummary, PublishStorageError> {
    let mut object_keys = Vec::with_capacity(plan.objects.len());
    let mut object_uploaded_count = 0usize;
    let mut object_skipped_count = 0usize;
    for object in &plan.objects {
        let relative_key = publish_ai_object_relative_key(
            &plan.bundle.revision_oid,
            ai_layer_label(object.object.layer),
            &object.object.object_type,
            &object.object.object_id,
        );
        if options.force || !storage.head(&relative_key).await? {
            storage.put_json(&relative_key, &object.object).await?;
            object_uploaded_count += 1;
        } else {
            object_skipped_count += 1;
        }
        object_keys.push(object.r2_key.clone());
    }

    let index_relative_key = publish_ai_index_relative_key(&plan.index.revision_oid);
    let index_uploaded = options.force || !storage.head(&index_relative_key).await?;
    if index_uploaded {
        storage.put_json(&index_relative_key, &plan.index).await?;
    }

    let graph_relative_key = publish_ai_graph_relative_key(&plan.graph.revision_oid);
    let graph_uploaded = options.force || !storage.head(&graph_relative_key).await?;
    if graph_uploaded {
        storage.put_json(&graph_relative_key, &plan.graph).await?;
    }

    let bundle_relative_key =
        publish_ai_bundle_relative_key(&plan.bundle.revision_oid, &plan.bundle.ai_version_id);
    let bundle_uploaded = options.force || !storage.head(&bundle_relative_key).await?;
    if bundle_uploaded {
        storage.put_json(&bundle_relative_key, &plan.bundle).await?;
    }

    Ok(AiExportArtifactUploadSummary {
        index_uploaded,
        graph_uploaded,
        bundle_uploaded,
        object_count: object_keys.len(),
        object_uploaded_count,
        object_skipped_count,
        object_keys,
    })
}

/// Build the D1 `publish_revisions` and `publish_files` rows for a
/// code-only revision snapshot.
///
/// The returned rows are ready for `D1Client::upsert_publish_revision`
/// and `D1Client::upsert_publish_file`. AI object/version rows are
/// deliberately not produced here; the AI exporter owns that surface.
pub fn build_revision_d1_rows(
    plan: &RevisionArtifactPlan,
    sync_run_id: &str,
    redaction_mode: RedactionMode,
    redaction_rules_version: &str,
) -> Result<RevisionD1Rows, RevisionD1RowsError> {
    let timestamp = plan.revision.generated_at.to_rfc3339();
    let file_count = i64::try_from(plan.code_manifest.files.len()).map_err(|_| {
        RevisionD1RowsError::FileCountTooLarge {
            count: plan.code_manifest.files.len(),
        }
    })?;
    let revision = PublishRevisionRow {
        site_id: plan.code_manifest.site_id.clone(),
        revision_oid: plan.revision.revision_oid.clone(),
        status: "published".to_string(),
        code_manifest_key: Some(plan.code_manifest_key.clone()),
        ai_index_key: None,
        file_count,
        ai_object_count: 0,
        ai_bundle_count: 0,
        redaction_mode: redaction_mode_label(redaction_mode).to_string(),
        redaction_rules_version: redaction_rules_version.to_string(),
        sync_run_id: sync_run_id.to_string(),
        schema_version: i64::from(PUBLISH_SCHEMA_VERSION),
        created_at: timestamp.clone(),
        updated_at: timestamp,
    };

    let mut files = Vec::with_capacity(plan.code_manifest.files.len());
    for file in &plan.code_manifest.files {
        let size_bytes =
            i64::try_from(file.size_bytes).map_err(|_| RevisionD1RowsError::FileSizeTooLarge {
                path: file.path.clone(),
                size_bytes: file.size_bytes,
            })?;
        files.push(PublishFileRow {
            site_id: file.site_id.clone(),
            revision_oid: file.revision_oid.clone(),
            path: file.path.clone(),
            display_mode: file_display_mode_label(file.display_mode).to_string(),
            content_sha256: file.content_sha256.clone(),
            r2_key: file.r2_key.clone(),
            size_bytes,
            language: file.language.clone(),
            schema_version: i64::from(PUBLISH_SCHEMA_VERSION),
        });
    }

    Ok(RevisionD1Rows { revision, files })
}

/// Build D1 `publish_refs` rows plus R2 `refs.json` and `latest.json`
/// payloads for a full all-refs sync.
pub fn build_site_index_artifacts(
    plan: &SnapshotPlan,
    site_id: &str,
    sync_run_id: &str,
    refs_generation: u64,
    generated_at: chrono::DateTime<chrono::Utc>,
) -> Result<SiteIndexArtifacts, SiteIndexArtifactError> {
    let default_ref = plan
        .default_ref
        .clone()
        .ok_or(SiteIndexArtifactError::MissingDefaultRef)?;
    let latest_revision_oid = plan
        .default_latest_revision_oid()
        .ok_or(SiteIndexArtifactError::MissingLatestRevision)?
        .to_string();
    let refs_index = plan.to_refs_index(site_id, refs_generation, generated_at)?;
    let latest = PublishSiteLatest {
        schema_version: PUBLISH_SCHEMA_VERSION,
        site_id: site_id.to_string(),
        default_ref,
        latest_revision_oid,
        refs_generation,
        updated_at: generated_at,
    };
    let updated_at = generated_at.to_rfc3339();
    let ref_rows = plan
        .refs
        .iter()
        .map(|publish_ref| PublishRefRow {
            site_id: site_id.to_string(),
            ref_name: publish_ref.ref_name.clone(),
            ref_type: ref_type_label(publish_ref.ref_type()).to_string(),
            short_name: publish_ref.short_name().to_string(),
            target_oid: publish_ref.target_oid.clone(),
            revision_oid: publish_ref.revision_oid.clone(),
            is_default: if publish_ref.is_default { 1 } else { 0 },
            sync_run_id: sync_run_id.to_string(),
            schema_version: i64::from(PUBLISH_SCHEMA_VERSION),
            updated_at: updated_at.clone(),
        })
        .collect();

    Ok(SiteIndexArtifacts {
        refs_index,
        latest,
        ref_rows,
    })
}

/// Build D1 `publish_ai_objects` and `publish_ai_versions` rows for
/// one AI export plan.
pub fn build_ai_export_d1_rows(plan: &AiExportPlan) -> Result<AiExportD1Rows, AiExportD1RowsError> {
    let created_at = plan.index.generated_at.to_rfc3339();
    let objects = plan
        .objects
        .iter()
        .map(|object| PublishAiObjectRow {
            site_id: object.object.site_id.clone(),
            revision_oid: object.object.revision_oid.clone(),
            object_type: object.object.object_type.clone(),
            object_id: object.object.object_id.clone(),
            layer: ai_layer_label(object.object.layer).to_string(),
            r2_key: object.r2_key.clone(),
            redaction_mode: redaction_mode_label(object.object.redaction.mode).to_string(),
            payload_sha256: object.payload_sha256.clone(),
            schema_version: i64::from(PUBLISH_SCHEMA_VERSION),
            created_at: created_at.clone(),
        })
        .collect::<Vec<_>>();
    let bundle = plan
        .index
        .bundles
        .first()
        .ok_or(AiExportD1RowsError::MissingBundle)?;
    let object_count =
        i64::try_from(objects.len()).map_err(|_| AiExportD1RowsError::ObjectCountTooLarge {
            count: objects.len(),
        })?;
    let version = PublishAiVersionRow {
        site_id: plan.bundle.site_id.clone(),
        ai_version_id: plan.bundle.ai_version_id.clone(),
        revision_oid: plan.bundle.revision_oid.clone(),
        bundle_key: plan.bundle_key.clone(),
        bundle_sha256: bundle.bundle_sha256.clone(),
        object_count,
        redaction_mode: redaction_mode_label(plan.bundle.redaction.mode).to_string(),
        redaction_rules_version: plan.bundle.redaction.rules_version.clone(),
        schema_version: i64::from(PUBLISH_SCHEMA_VERSION),
        created_at,
    };

    Ok(AiExportD1Rows { objects, version })
}

fn redaction_mode_label(mode: RedactionMode) -> &'static str {
    match mode {
        RedactionMode::Default => "default",
        RedactionMode::Strict => "strict",
    }
}

fn file_display_mode_label(mode: FileDisplayMode) -> &'static str {
    match mode {
        FileDisplayMode::Text => "text",
        FileDisplayMode::Binary => "binary",
        FileDisplayMode::TooLarge => "too_large",
        FileDisplayMode::Ignored => "ignored",
    }
}

fn ref_type_label(ref_type: RefType) -> &'static str {
    match ref_type {
        RefType::Branch => "branch",
        RefType::Tag => "tag",
    }
}

fn ai_layer_label(layer: AiObjectLayer) -> &'static str {
    match layer {
        AiObjectLayer::Snapshot => "snapshot",
        AiObjectLayer::Event => "event",
        AiObjectLayer::Projection => "projection",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pin the `Display` format contract for the three small typed
    /// error enums in this module:
    ///   - `RevisionD1RowsError`
    ///   - `SiteIndexArtifactError`
    ///   - `AiExportD1RowsError`
    ///
    /// These surface in `cloud sync` failure paths and are mapped to
    /// `StableErrorCode::ConflictOperationBlocked` /
    /// `IoWriteFailed` at the CLI boundary. Future refactors that
    /// touch the `#[error(...)]` attributes will trip this test.
    #[test]
    fn publish_upload_error_display_pins_each_variant() {
        // RevisionD1RowsError
        let e = RevisionD1RowsError::FileCountTooLarge { count: 1_000_000 };
        assert_eq!(
            e.to_string(),
            "publish revision file count 1000000 exceeds D1 integer range",
        );
        let e = RevisionD1RowsError::FileSizeTooLarge {
            path: "src/big.bin".to_string(),
            size_bytes: 9_223_372_036_854_775_807, // i64::MAX
        };
        assert_eq!(
            e.to_string(),
            "publish file \"src/big.bin\" has size 9223372036854775807 \
             which exceeds D1 integer range",
        );

        // SiteIndexArtifactError (skip the #[from] Snapshot variant —
        // its Display is owned by SnapshotBuildError).
        assert_eq!(
            SiteIndexArtifactError::MissingDefaultRef.to_string(),
            "site index requires a default ref",
        );
        assert_eq!(
            SiteIndexArtifactError::MissingLatestRevision.to_string(),
            "site index requires the default ref to resolve to a latest revision",
        );

        // AiExportD1RowsError
        assert_eq!(
            AiExportD1RowsError::ObjectCountTooLarge { count: 5_000_000 }.to_string(),
            "AI export object count 5000000 exceeds D1 integer range",
        );
        assert_eq!(
            AiExportD1RowsError::MissingBundle.to_string(),
            "AI export plan does not contain a bundle entry",
        );
    }
}
