//! Denormalized reverse indexes for the Libra runtime layer.
//!
//! These rows are rebuildable query accelerators over immutable snapshot and
//! event history. They make common traversals such as `intent -> plan`,
//! `task -> run`, and `run -> patchset` cheap without changing the underlying
//! object graph defined in `docs/agent/agent.md`.
//!
//! TODO(test): add CRUD coverage for the corresponding `ai_index_*` SeaORM
//! entities when the projector starts materializing these rows.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Denormalized index row for resolving intent -> plan relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct IntentPlanIndexRow {
    /// Intent snapshot that owns or produced the Plan.
    pub intent_id: Uuid,
    /// Plan snapshot reachable from the Intent.
    pub plan_id: Uuid,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}

/// Denormalized index row for resolving intent -> task relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct IntentTaskIndexRow {
    /// Intent snapshot that the Task belongs to.
    pub intent_id: Uuid,
    /// Task snapshot reachable from the Intent.
    pub task_id: Uuid,
    /// Optional parent task when the Task is part of a task hierarchy.
    pub parent_task_id: Option<Uuid>,
    /// Optional originating Plan step that produced the Task definition.
    pub origin_step_id: Option<Uuid>,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}

/// Denormalized index row for resolving plan step -> task relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PlanStepTaskIndexRow {
    /// Plan snapshot that contains the step.
    pub plan_id: Uuid,
    /// Stable logical step identifier within the Plan.
    pub step_id: Uuid,
    /// Task snapshot delegated from the Plan step.
    pub task_id: Uuid,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}

/// Denormalized index row for resolving task -> run relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TaskRunIndexRow {
    /// Task snapshot that owns the Run attempts.
    pub task_id: Uuid,
    /// Run snapshot linked to the Task.
    pub run_id: Uuid,
    /// Whether this row points at the latest known Run for the Task.
    pub is_latest: bool,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}

/// Denormalized index row for resolving run -> event relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RunEventIndexRow {
    /// Run snapshot that owns the event stream.
    pub run_id: Uuid,
    /// Concrete event object linked to the Run.
    pub event_id: Uuid,
    /// Event discriminator used for filtering and UI grouping.
    pub event_kind: String,
    /// Whether this row points at the latest known event for the Run.
    pub is_latest: bool,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}

/// Denormalized index row for resolving run -> patchset relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RunPatchSetIndexRow {
    /// Run snapshot that produced the PatchSet.
    pub run_id: Uuid,
    /// PatchSet snapshot generated by the Run.
    pub patchset_id: Uuid,
    /// Monotonic PatchSet order within the Run.
    pub sequence: i64,
    /// Whether this row points at the latest known PatchSet for the Run.
    pub is_latest: bool,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}

/// Denormalized index row for resolving intent -> context frame relationships.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct IntentContextFrameIndexRow {
    /// Intent snapshot associated with the ContextFrame.
    pub intent_id: Uuid,
    /// ContextFrame event linked back to the Intent.
    pub context_frame_id: Uuid,
    /// Relation label describing how the frame is associated with the Intent.
    pub relation_kind: String,
    /// Time at which Libra materialized this reverse index row.
    pub created_at: DateTime<Utc>,
}
